config/routes.rb
Rails.application.routes.draw do
  resources :emps
  
  root 'emps#index'
  get 'emps/new'
  get 'emps/show'
  get 'emps/form'
  get 'emps/edit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/emp.rb
class Emp < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/emps_controller.rb
class EmpsController < ApplicationController
  before_action :set_emp, only: %i[ show edit update destroy ]

  # GET /emps or /emps.json
  def index
    @emps = Emp.all
  end

  # GET /emps/1 or /emps/1.json
  def show
  end

  # GET /emps/new
  def new
    @emp = Emp.new
  end

  # GET /emps/1/edit
  def edit
  end

  # POST /emps or /emps.json
  def create
    @emp = Emp.new(emp_params)

    respond_to do |format|
      if @emp.save
        format.html { redirect_to @emp, notice: "Emp was successfully created." }
        format.json { render :show, status: :created, location: @emp }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @emp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emps/1 or /emps/1.json
  def update
    respond_to do |format|
      if @emp.update(emp_params)
        format.html { redirect_to @emp, notice: "Emp was successfully updated." }
        format.json { render :show, status: :ok, location: @emp }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @emp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emps/1 or /emps/1.json
  def destroy
    @emp.destroy
    respond_to do |format|
      format.html { redirect_to emps_url, notice: "Emp was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emp
      @emp = Emp.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def emp_params
      params.require(:emp).permit(:name, :age, :gender, :designation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emps_helper.rb
module EmpsHelper
end

app/views/emps/_form.html.erb
<%= form_with(model: emp) do |form| %>
  <% if emp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(emp.errors.count, "error") %> prohibited this emp from being saved:</h2>

      <ul>
        <% emp.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="container">
    <h1>Add Employee</h1>
  <div class="field">
  <div class="form-group">
  <label for="name" class="text-dark">Name OF Employee</label>
    <%= form.text_field :name, :class=>"form-control" %>
  </div>
</div>

   <div class="field">
  <div class="form-group">
  <label for="age" class="text-dark">Age</label>
    <%= form.text_field :age,  :class=>"form-control" %>
  </div>
</div>

  <div class="field">
  <div class="form-group">
  <label for="gender" class="text-dark">Gender</label>
  <%= form.text_field :gender, :class=>"form-control" %>
  </div>
</div>


  <div class="field">
  <div class="form-group">
  <label for="designation" class="text-dark">Designation </label>
  <%= form.text_field :designation, :class=>"form-control" %>
  </div>
</div>

  <div class="actions"><center>
    <%= form.submit :class=>"btn btn-warning" %></center>
  </div>
</div>
<% end %>

app/views/emps/edit.html.erb
<h1 class="heading">Editing Employee</h1>

<%= render 'form', emp: @emp %>
<div class="below">
<%= link_to 'Show', @emp,:class=>"btn btn-warning" %> |
<%= link_to 'Back', emps_path,:class=>"btn btn-info" %>
</div>

app/views/emps/index.html.erb
<h1 class="heading">Employee management system</h1>

<table class="table table-bordered">
  <thead class="table table-bordered table-dark">
    <tr align="center">
       <th scope="col" >Name</th>
      <th scope="col">Age</th>
      <th scope="col">Gender</th>
      <th scope="col">Designation</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @emps.each do |emp| %>
      <tr>
        <td><%= emp.name %></td>
        <td><%= emp.age %></td>
        <td><%= emp.gender %></td>
        <td><%= emp.designation %></td>
        <td><%= link_to 'Show', emp, :class=>"link-primary" %></td>
        <td><%= link_to 'Edit', edit_emp_path(emp), :class=>"link-secondary" %></td>
        <td><%= link_to 'Destroy', emp, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"link-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<center><%= link_to 'ADD', new_emp_path, :class=>"btn btn-warning"%></center>

app/views/emps/new.html.erb
<h1 class="heading">Employee Management system</h1>

<%= render 'form', emp: @emp %>

<%= link_to 'Back', emps_path %>

app/views/emps/show.html.erb
<h1 class="heading">Employee management system</h1>

<p id="notice"><%= notice %></p>
<div class="card" style="width:18rem;">
	<div class="card-header">
		New Employee Been Added
	</div>
	<div class="card-body">
<p>
  <strong>Name:</strong>
  <%= @emp.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @emp.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @emp.gender %>
</p>

<p>
  <strong>Designation:</strong>
  <%= @emp.designation %>
</p>

<%= link_to 'Edit', edit_emp_path(@emp), :class=>"btn btn-warning" %> |
<%= link_to 'Back', emps_path, :class=>"btn btn-info" %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employee</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>